name: GitHub Metrics

on:
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      REPO: ModarRostom/ModarRostom
    steps:
      - name: Preflight – verify repo & branch with PAT
        run: |
          set -euo pipefail
          echo "Checking $REPO branch $BRANCH"
          code_repo=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${METRICS_TOKEN}" \
            https://api.github.com/repos/${REPO})
          echo "GET /repos => $code_repo"
          code_ref=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${METRICS_TOKEN}" \
            https://api.github.com/repos/${REPO}/git/ref/heads/${BRANCH})
          echo "GET /git/ref/heads/${BRANCH} => $code_ref"
          if [ "$code_repo" != "200" ] || [ "$code_ref" != "200" ]; then
            echo "ERROR: 404/401/403 bedeuten: Repo-Name/Branch falsch oder PAT/Secret falsch bzw. ohne 'repo'-Rechte."
            exit 1
          fi
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}             # API lesen
          committer_token: ${{ secrets.METRICS_TOKEN }}   # SVG committen
          committer_repository: ModarRostom/ModarRostom
          committer_branch: main

          # Profil
          user: ModarRostom
          config_timezone: Europe/Berlin

          # Schlankes Layout
          template: classic
          base: header, activity, metadata

          # Aktivität (entspricht Radar-Inhalt)
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 10

          # Commit-Kalender (Heatmap)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Achievements
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # Deaktiviert
          plugin_languages: no
          plugin_lines: no
          plugin_followup: no
          plugin_calendar: no

          # Ausgabe
          output_action: commit
          committer_message: "chore(metrics): update metrics"
          filename: metrics.svg
