name: GitHub Metrics

on:
  schedule:
    - cron: "17 5 * * *"      # täglich
  workflow_dispatch: {}        # manueller Start
  push:
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}            # API lesen
          committer_token: ${{ secrets.METRICS_TOKEN }}  # SVG committen

          # Profil
          user: ModarRostom
          config_timezone: Europe/Berlin

          # Schlankes Layout
          template: classic
          base: header, activity, metadata

          # Aktivität (entspricht inhaltlich dem Radar: Commits/PRs/Reviews/Issues)
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 10

          # Heatmap (Commit-Kalender)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # Achievements (runde Icons)
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # Deaktiviert: alles Überflüssige
          plugin_languages: no
          plugin_lines: no
          plugin_followup: no
          plugin_calendar: no

          # Ausgabe
          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update metrics"
          filename: metrics.svg
