name: GitHub Profile Metrics

on:
  schedule:
    - cron: '23 3 * * *'     # 1x täglich reicht
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Profil
          user: ModarRostom
          template: classic
          config_timezone: Europe/Berlin

          # Nur die Basisköpfe + wenig Meta
          base: header, metadata

          #### Contribution-Heatmap (ähnlich der GitHub-Heatmap)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full   # ganzes Jahr

          #### Achievements (ähnlich der linken Trophäen)
          plugin_achievements: yes
          plugin_achievements_display: detailed   # oder 'compact'
          plugin_achievements_threshold: C        # ab Level C zeigen
          plugin_achievements_secrets: yes

          #### Leichte Aktivitätsstatistiken (Ersatz fürs Radar)
          plugin_habits: yes
          plugin_habits_from: 200    # Tage zurück
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          #### Optional: Sprachen-Balken (nur wenn du willst)
          plugin_languages: no        # auf 'yes' stellen, falls erwünscht

          # Ausgabedatei
          filename: metrics.svg
