name: GitHub Profile Metrics

on:
  schedule:
    - cron: '23 3 * * *'    # 1x täglich
  workflow_dispatch: {}
  push:
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # für den Commit von metrics.svg
    steps:
      - uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: ModarRostom
          template: classic
          base: header, metadata
          config_timezone: Europe/Berlin

          # Heatmap (ähnlich GitHub)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full

          # Aktivitäts-Gewohnheiten (Ersatz fürs Radar)
          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          # Achievements stabil (ohne private/secret Daten)
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C
          plugin_achievements_secrets: no
          plugin_achievements_limit: 12

          filename: metrics.svg
