name: GitHub Metrics

on:
  schedule:
    - cron: "17 5 * * *"      # 1x täglich
  workflow_dispatch: {}        # manueller Start
  push:
    paths:
      - ".github/workflows/metrics.yml"

# WICHTIG: erlaubt dem Workflow Commits zu schreiben (falls auf GITHUB_TOKEN zurückgegriffen wird)
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # --- Authentifizierung ---
          # Token für API-Abfragen (GitHub API)
          token: ${{ secrets.METRICS_TOKEN }}
          # Token zum Committen der erzeugten SVG ins Repo (explizit setzen!)
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # --- Allgemeine Einstellungen ---
          user: ModarRostom
          config_timezone: Europe/Berlin
          template: classic
          base: header, activity, community, repositories, metadata

          # --- Aktivität (entspricht Radar-Inhalt: Commits, PRs, Reviews, Issues) ---
          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 20

          # --- Jahres-Heatmap ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          # --- Achievements (runde Icons) ---
          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          # --- Sprachen + geänderte Zeilen ---
          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes

          # --- Follow-up-Statistiken ---
          plugin_followup: yes
          plugin_followup_sections: repositories, user

          # --- Ausgabe/Commit ---
          output_action: commit
          committer_branch: main                 # falls dein Default-Branch anders heißt, hier anpassen
          committer_message: "chore(metrics): update metrics"
          filename: metrics.svg
