name: GitHub Metrics

on:
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/metrics.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ModarRostom
          config_timezone: Europe/Berlin

          template: classic
          base: header, activity, community, repositories, metadata

          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 20

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          plugin_languages: yes
          plugin_languages_limit: 12
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          output_action: commit
          committer_branch: main
          committer_message: "chore(metrics): update metrics"
          filename: metrics.svg
