name: GitHub Profile Metrics

on:
  schedule:
    - cron: '21 */12 * * *'   # alle 12 Stunden
  workflow_dispatch: {}        # manuell starten möglich
  push:
    paths:
      - '.github/workflows/metrics.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # SVG ins Repo committen
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Grundkonfiguration
          user: ModarRostom
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Berlin

          # Plugins (Auswahl)
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_isocalendar: yes           # Wochen-Heatmap
          plugin_isocalendar_duration: full # ganzes Jahr

          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_details: percentage
          plugin_languages_limit: 8

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_stars: yes
          plugin_stars_limit: 4

          # Ausgabeziel
          filename: metrics.svg
