name: GitHub Metrics

on:
  schedule:
    - cron: "17 5 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BRANCH: main
      REPO: ModarRostom/ModarRostom
    steps:
      - name: Preflight – check branch access with PAT
        run: |
          set -euo pipefail
          echo "Checking ref heads/${BRANCH} on ${REPO}"
          code=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${METRICS_TOKEN}" \
            https://api.github.com/repos/${REPO}/git/ref/heads/${BRANCH})
          if [ "$code" != "200" ]; then
            echo "ERROR: API returned HTTP $code for heads/${BRANCH}. Check: repo name, branch name, PAT scopes (repo, read:user), and that the secret METRICS_TOKEN is the NEW classic token."
            exit 1
          fi
        env:
          METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          # Auth
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}

          # Ziel explizit setzen (verhindert 404 auf falschem Repo/Branch)
          committer_repository: ModarRostom/ModarRostom
          committer_branch: main

          # Profil
          user: ModarRostom
          config_timezone: Europe/Berlin

          # Schlankes Layout (Aktivität, Heatmap, Achievements)
          template: classic
          base: header, activity, metadata

          plugin_activity: yes
          plugin_activity_days: 30
          plugin_activity_filter: all
          plugin_activity_limit: 10

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact

          plugin_languages: no
          plugin_lines: no
          plugin_followup: no
          plugin_calendar: no

          output_action: commit
          committer_message: "chore(metrics): update metrics"
          filename: metrics.svg
